//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planta
    {
        public int Id { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Nombre { get; set; }
        public string Longitud_promedio { get; set; }
        public string Temporada { get; set; }
        public string Luz_exposicion { get; set; }
        public string Riego { get; set; }
        public string Tipo_suelo { get; set; }
        public string Otros { get; set; }
    }
}
